---
version: "3"
services:
  dinnerclub_app:
    container_name: dinnerclub_app
    build:
      dockerfile: Dockerfile
      context: .
    image: toozej/dinnerclub:latest
    restart: unless-stopped
    env_file:
      - "./app.env"
    volumes:
      - "./app.env:/app.env"
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.dinnerclub.rule=Host(`dinnerclub.test`)"
      - "traefik.http.routers.dinnerclub.middlewares=http-redirect-https@file,headers@file"
      - "traefik.http.routers.dinnerclub-secure.entrypoints=https"
      - "traefik.http.routers.dinnerclub-secure.rule=Host(`dinnerclub.test`)"
      - "traefik.http.routers.dinnerclub-secure.middlewares=headers@file"
      - "traefik.http.routers.dinnerclub-secure.tls=true"
    networks:
      - traefik
      - backend
  dinnerclub_pgsql:
    image: postgres:14
    container_name: dinnerclub_pgsql
    restart: unless-stopped
    env_file:
      - "./db.env"
    volumes:
      - "dinnerclub_pgsql:/var/lib/postgresql/data"
    labels:
      - "traefik.enable=false"
    networks:
      - backend
volumes:
  dinnerclub_pgsql:
    driver_opts:
      type: tmpfs
      device: tmpfs
networks:
  traefik:
    name: traefik
    external: true
  backend:
    driver: bridge
