---
version: "3"
services:
  dinnerclub:
    container_name: dinnerclub
    image: toozej/dinnerclub:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
      # labels below for publishing as web service
      # - "traefik.docker.network=traefik"
      # - "traefik.http.routers.dinnerclub.rule=Host(`dinnerclub.test`)"
      # - "traefik.http.routers.dinnerclub.middlewares=http-redirect-https@file,headers@file"
      # - "traefik.http.routers.dinnerclub-secure.entrypoints=https"
      # - "traefik.http.routers.dinnerclub-secure.rule=Host(`dinnerclub.test`)"
      # - "traefik.http.routers.dinnerclub-secure.middlewares=headers@file"
      # - "traefik.http.routers.dinnerclub-secure.tls=true"
    # networks:
      # - traefik
